services:
  db:
    image: postgres:latest
    container_name: backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - 8080:8080